#!/bin/bash
#SBATCH -A see200002p
#SBATCH -J myjob
export OMP_NUM_THREADS=2
#export OMP_NUM_THREADS=4
#export OMP_NUM_THREADS=8
#export OMP_NUM_THREADS=16
nvc -mp -Minfo=accel -o matrix_openmp matrix_openmp.c
./matrix_openmp
